### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by AltyFox** [cal117/Colorama#2]
These two mods (colorama and vent) are causing players mods to break.  It's installing an older version of code gen somehow and disabling all other mods.

**Comment by AltyFox** [comment]
https://discord.com/channels/441805394323439646/599740612752703490/1051415639799111751

https://discord.com/channels/441805394323439646/599740612752703490/1049873175120445513



For reference.  There's more but I'm too lazy to look

**Comment by IMB11** [comment]
Do you know what version of codegen is for 1.25.1?

**Comment by IMB11** [comment]
Fixed. Redownload. If you want, you can tell people affected to redownload, would help lots thanks :+1:
